const FETCH_SINGLE_ITEM_REQUEST = 'item/FETCH_SINGLE_ITEM_REQUEST';
const FETCH_SINGLE_ITEM_SUCCESS = 'item/FETCH_SINGLE_ITEM_SUCCESS';
const FETCH_SINGLE_ITEM_FAILED = 'item/FETCH_SINGLE_ITEM_FAILED';

export default {
  FETCH_SINGLE_ITEM_REQUEST,
  FETCH_SINGLE_ITEM_SUCCESS,
  FETCH_SINGLE_ITEM_FAILED,
};
