const SIGN_UP_REQUEST = 'auth/SIGN_UP_REQUEST';
const SIGN_UP_SUCCESS = 'auth/SIGN_UP_SUCCESS';
const SIGN_UP_FAILED = 'auth/SIGN_UP_FAILED';

const SIGN_IN_REQUEST = 'auth/SIGN_IN_REQUEST';
const SIGN_IN_SUCCESS = 'auth/SIGN_IN_SUCCESS';
const SIGN_IN_FAILED = 'auth/SIGN_IN_FAILED';

const SIGN_OUT_REQUEST = 'auth/SIGN_OUT_REQUEST';
const SIGN_OUT_SUCCESS = 'auth/SIGN_OUT_SUCCESS';

const REFRESH_CURRENT_USER_REQUEST = 'auth/REFRESH_CURRENT_USER_REQUEST';
const REFRESH_CURRENT_USER_SUCCESS = 'auth/REFRESH_CURRENT_USER_SUCCESS';

export default {
  SIGN_UP_REQUEST,
  SIGN_UP_SUCCESS,
  SIGN_UP_FAILED,
  SIGN_OUT_REQUEST,
  SIGN_OUT_SUCCESS,
  SIGN_IN_REQUEST,
  SIGN_IN_SUCCESS,
  SIGN_IN_FAILED,
  REFRESH_CURRENT_USER_REQUEST,
  REFRESH_CURRENT_USER_SUCCESS,
};
