const FETCH_ALL_REQUEST = 'menu/FETCH_ALL_REQUEST';
const FETCH_ALL_SUCCESS = 'menu/FETCH_ALL_SUCCESS';
const FETCH_ALL_FAILED = 'menu/FETCH_ALL_FAILED';

const DELETE_REQUEST = 'item/DELETE_REQUEST';
const DELETE_SUCCESS = 'item/DELETE_SUCCESS';
const DELETE_FAILED = 'item/DELETE_FAILED';

export default {
  FETCH_ALL_REQUEST,
  FETCH_ALL_SUCCESS,
  FETCH_ALL_FAILED,
  DELETE_REQUEST,
  DELETE_SUCCESS,
  DELETE_FAILED,
};
