const FETCH_ALL_REQUEST = 'menu/FETCH_ALL_REQUEST';
const FETCH_ALL_SUCCESS = 'menu/FETCH_ALL_SUCCESS';
const FETCH_ALL_FAILED = 'menu/FETCH_ALL_FAILED';

export default {
  FETCH_ALL_REQUEST,
  FETCH_ALL_SUCCESS,
  FETCH_ALL_FAILED,
};
